(venv) Î» python test_ranking.py 
..EEEE
======================================================================
ERROR: test_03_ranking_keys (__main__.TestApp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Creation\Programming\stella-micro-template-elastic\test\test_ranking.py", line 33, in
    keys = json.loads(res.content).keys()
  File "C:\Users\vimio\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, i
    return _default_decoder.decode(s)
  File "C:\Users\vimio\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\vimio\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

======================================================================
ERROR: test_04_ranking_key_contents (__main__.TestApp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Creation\Programming\stella-micro-template-elastic\test\test_ranking.py", line 43, in
    content = json.loads(res.content)
  File "C:\Users\vimio\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, i
    return _default_decoder.decode(s)
  File "C:\Users\vimio\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\vimio\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

======================================================================
ERROR: test_05_ranking_not_empty (__main__.TestApp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Creation\Programming\stella-micro-template-elastic\test\test_ranking.py", line 51, in
    content = json.loads(res.content)
  File "C:\Users\vimio\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, i
    return _default_decoder.decode(s)
  File "C:\Users\vimio\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\vimio\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

======================================================================
ERROR: test_06_ranking_length (__main__.TestApp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Creation\Programming\stella-micro-template-elastic\test\test_ranking.py", line 57, in
    content = json.loads(res.content)
  File "C:\Users\vimio\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, i
    return _default_decoder.decode(s)
  File "C:\Users\vimio\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\vimio\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------
Ran 6 tests in 1031.235s

FAILED (errors=4)